## 단항 유니버설 함수

In [1]:
import numpy as np

# 반올림: 수점을 반올림
np.around([1.1, -1.6, 2, -2.7, 2.01, -2.01])

array([ 1., -2.,  2., -3.,  2., -2.])

In [2]:
# 올림: 주어진 값과 같은 정수 혹은 큰 가장 가까운 정수을 반환
np.ceil([1.1, -1.6, 2, -2.7, 2.01, -2.01])

array([ 2., -1.,  2., -2.,  3., -2.])

In [3]:
# 내림: 주어진 값과 같은 정수 혹은 작은 가장 가까운 정수 반환
np.floor([1.1, -1.6, 2, -2.7, 2.01, -2.01])

array([ 1., -2.,  2., -3.,  2., -3.])

In [4]:
# 버림: 소수점 이하 버림
np.trunc([1.1, -1.6, 2, -2.7, 2.01, -2.01])

array([ 1., -1.,  2., -2.,  2., -2.])

In [5]:
# 가장 가까운 정수로 반올림
np.rint([1.1, -1.6, 2, -2.7, 2.01, -2.01])

array([ 1., -2.,  2., -3.,  2., -2.])

In [6]:
# 0쪽으로 가장 가까운 정수로 반올림
np.fix([1.1, -1.6, 2, -2.7, 2.01, -2.01])

array([ 1., -1.,  2., -2.,  2., -2.])

In [7]:
# 절대값 구하기: 정수, 부동소수점수, 복소수
np.abs([1.1, -1.6, 2, -2.7, 2.01, -2.01, 1+2j])

array([1.1       , 1.6       , 2.        , 2.7       , 2.01      ,
       2.01      , 2.23606798])

In [8]:
np.absolute([1.1, -1.6, 2, -2.7, 2.01, -2.01, 1+2j])

array([1.1       , 1.6       , 2.        , 2.7       , 2.01      ,
       2.01      , 2.23606798])

In [9]:
# 절대값 구하기: 정수, 부동소수점수 (abs보다 빠름)
np.fabs([1.1, -1.6, 2, -2.7, 2.01, -2.01])

array([1.1 , 1.6 , 2.  , 2.7 , 2.01, 2.01])

In [10]:
# 제곱근 구하기
np.sqrt([1,4,9,21])

array([1.        , 2.        , 3.        , 4.58257569])

In [11]:
# 큐브루트(세제곱근)구하기
np.cbrt([1,8,27])

array([1., 2., 3.])

In [12]:
# 제곱값 구하기
np.square([1,4,9,21])

array([  1,  16,  81, 441])

In [13]:
# 소수와 정수 부분으로 나누기
np.modf([1.1, -1.6, 2, -2.7, 2.01, -2.01, 0])

(array([ 0.1 , -0.6 ,  0.  , -0.7 ,  0.01, -0.01,  0.  ]),
 array([ 1., -1.,  2., -2.,  2., -2.,  0.]))

In [14]:
# 부호 판별: 1(양수), 0(영), -1(음수)
np.sign([1.1, -1.6, 2, -2.7, 2.01, -2.01, 0])

array([ 1., -1.,  1., -1.,  1., -1.,  0.])

In [15]:
# 복소수의 허수부분의 부호 변경
np.conj([1+2j, 1-3j, 2-6j])

array([1.-2.j, 1.+3.j, 2.+6.j])

In [16]:
np.conjugate([1+2j, 1-3j, 2-6j])

array([1.-2.j, 1.+3.j, 2.+6.j])

In [17]:
# 1 곱하기
np.positive([1.1, -1.6, 2, -2.7, 2.01, -2.01])

array([ 1.1 , -1.6 ,  2.  , -2.7 ,  2.01, -2.01])

In [18]:
# 부호변경: -1를 곱하기
np.negative([1.1, -1.6, 2, -2.7, 2.01, -2.01])

array([-1.1 ,  1.6 , -2.  ,  2.7 , -2.01,  2.01])

In [19]:
# 배열의 최대값
np.max([1.1, -1.6, 2, -2.7, 2.01, -2.01])

2.01

In [20]:
# 배열의 최소값
np.min([1.1, -1.6, 2, -2.7, 2.01, -2.01])

-2.7

In [21]:
# 배열의 최대값의 인덱스
np.argmax([1.1, -1.6, 2, -2.7, 2.01, -2.01])

4

In [22]:
#배열의 최소값의 인덱스
np.argmin([1.1, -1.6, 2, -2.7, 2.01, -2.01])

3

In [23]:
# 백분위 25%
np.percentile([1.1, -1.6, 2, -2.7, 2.01, -2.01], 25)

-1.9074999999999998

In [24]:
# 백분위 50%
np.percentile([1.1, -1.6, 2, -2.7, 2.01, -2.01], 50)

-0.25

In [25]:
# 중앙값 구하기
np.median([1.1, -1.6, 2, -2.7, 2.01, -2.01])

-0.25

In [26]:
# 평균값
np.mean([1.1, -1.6, 2, -2.7, 2.01, -2.01])

-0.20000000000000004

In [27]:
#요소를 [e^요소값] 구하기
np.exp([1,2,3,4,5])


array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [28]:
# 요소를 [2^요소값] 구하기
np.exp2([1,2,3,4,5])

array([ 2.,  4.,  8., 16., 32.])

In [29]:
# 밑이 e인 로그
np.log([0.0000000002, 2, 6])


array([-22.33270375,   0.69314718,   1.79175947])

In [30]:
# 밑이 e인 로그. 다만 log(1+x) 형태를 갖음; log에서 값이 0에 가까우면 발산하는 점을 보완함
np.log1p([0.0000000002, 2, 6])

array([2.00000000e-10, 1.09861229e+00, 1.94591015e+00])

In [31]:
#밑이 2인 로그
np.log2([0.0000000002, 2, 6])

array([-32.21928095,   1.        ,   2.5849625 ])

In [32]:
# 밑이 10인 로그
np.log10([0.0000000002, 2, 6])

array([-9.69897   ,  0.30103   ,  0.77815125])

In [33]:
# NaN 이면 True, 그외 False 반환
np.isnan([np.nan, np.inf, np.log1p(2), 2.])

array([ True, False, False, False])

In [34]:
# 유한수이면 True, 그외 False 반환
np.isfinite([1.,2.,4.,5., np.nan, np.inf, np.NINF])

array([ True,  True,  True,  True, False, False, False])

In [35]:
# 무한수이면 True, 그외 False 반환
np.isinf([1.,2.,4.,5., np.nan, np.inf, np.NINF])

array([False, False, False, False, False,  True,  True])

In [36]:
#역수(1/요소값) 구하기
np.reciprocal([1.,2.,4.,5.])

array([1.  , 0.5 , 0.25, 0.2 ])

In [37]:
# 논리 NOT 연산
np.logical_not([True, True, True, False])

array([False, False, False,  True])