## 배열 정렬하기

In [1]:
import numpy as np
x = np.random.normal(1,1,size=(3,3))
x

array([[ 0.99318113,  0.25492373,  1.82037376],
       [ 1.35216832, -1.23544579,  0.37357579],
       [ 0.64225876,  0.17267481,  0.96793795]])

In [2]:
# 각 행의 요소를 정렬
np.sort(x)

array([[ 0.25492373,  0.99318113,  1.82037376],
       [-1.23544579,  0.37357579,  1.35216832],
       [ 0.17267481,  0.64225876,  0.96793795]])

In [3]:
# 각 열의 요소를 정렬
np.sort(x, axis=0)

array([[ 0.64225876, -1.23544579,  0.37357579],
       [ 0.99318113,  0.17267481,  0.96793795],
       [ 1.35216832,  0.25492373,  1.82037376]])

In [4]:
# 역순으로 정렬
np.sort(x, axis=1)[::-1]

array([[ 0.17267481,  0.64225876,  0.96793795],
       [-1.23544579,  0.37357579,  1.35216832],
       [ 0.25492373,  0.99318113,  1.82037376]])

In [5]:
# 오름차순 정렬시의 인덱스
np.argsort(x)

array([[1, 0, 2],
       [1, 2, 0],
       [1, 0, 2]], dtype=int64)

In [6]:
import numpy as np
x1 = np.array([10, 20, 30, 10, 10])
y1 = np.array([40, 10, 10, 20, 30])
idx = np.lexsort((y1, x1))
idx

array([3, 4, 0, 1, 2], dtype=int64)

In [7]:
for i in idx:
  print(x1[i], y1[i])

10 20
10 30
10 40
20 10
30 10


## 배열 집합 메서드

In [8]:
import numpy as np

x = [1,2,2,2,3,3,4,4,5,5,5,6]
y = [1,1,1,2,3,4,4,4,5,6,6,7,7]
np.unique(x)

array([1, 2, 3, 4, 5, 6])

In [9]:
np.union1d(x,y) #x, y 합집합을 구한 후, 고유값 반환

array([1, 2, 3, 4, 5, 6, 7])

In [10]:
np.intersect1d(x,y) #x, y 교집합을 구한 후, 고유값 반환

array([1, 2, 3, 4, 5, 6])

In [13]:
np.setdiff1d(y, x) #x의 y 차집합을 구한 후, 교유값 반환

array([7])

In [12]:
np.in1d(y,x) #x 요소가 y에 포함되는지 불리언 반환

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False])