## ndarray 다루기

In [1]:
import numpy as np

# numpy 기초
a = np.array([0,1,2,3,4,5]) # 1차원 배열
b = np.array([(0,1,2), (3,4,5)]) # 2차원 배열
c = np.array([[[0,1,2],
               [3,4,5]],
             [[6,7,8],
               [9,10,11]]]) # 3차원 배열 2x2x3

print("a: ", a)
print("type(a): ", type(a))
print("b: ", b)
print("c: ", c)

print(len(c)) # 3차원 배열 깊이
print(len(c[0])) # 3차원 배열 행
print(len(c[0][0])) # 3차원 배열 열

a:  [0 1 2 3 4 5]
type(a):  <class 'numpy.ndarray'>
b:  [[0 1 2]
 [3 4 5]]
c:  [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
2
2
3


In [2]:
# 배열 생성 함수를 활용한 배열 만들기
z1 = np.zeros(3) # '0' 3개 요소 1차원 배열
z2 = np.zeros((3,3)) # '0' 3x3개 요소 2차원 배열 
one1 = np.ones(3)  # '1' 3개 요소 1차원 배열
one2 = np.ones((3,3)) # '1' 3x3개 요소 2차원 배열 

print("zero1: ", z1)
print("zero2: ", z2)
print("one1: ", one1)
print("one2: ", one2)

# '0'부터 '6'미만까지 '1'씩 증가하는 1차원 수열 
#(빌트인 함수 range와 유사)
ar1 = np.arange(0, 6, 1, dtype=np.int8)
print("arange " , ar1)

lin1 = np.linspace(1, 2, 3)

#초기화되지 않은 값으로 배열을 생성
print("empty(5): ", np.empty(5))
e1 = np.empty((2,3))

# 4x4 단위행렬 만들기
e2 = np.eye(4)

# 2x3배열을 만드록, 20 값으로 모두 채움
f1 = np.full((2,3),20)

# 표준정규분포 난수
ran1 = np.random.rand(2,3)
# 가우시안 표준정규분포 난수
ran2 = np.random.randn(2,3)


print("linspace: " , lin1)
print("empty: " , e1)
print("eye: " , e2)
print("full: ", f1)
print("random1: ", ran1)
print("random2: ", ran2)

zero1:  [0. 0. 0.]
zero2:  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
one1:  [1. 1. 1.]
one2:  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
arange  [0 1 2 3 4 5]
empty(5):  [2.12199579e-314 0.00000000e+000 2.82605549e-321 6.55696700e-312
 0.00000000e+000]
linspace:  [1.  1.5 2. ]
empty:  [[3.44900708e-307 4.22786102e-307 2.78145267e-307]
 [4.00537061e-307 9.45708167e-308 0.00000000e+000]]
eye:  [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
full:  [[20 20 20]
 [20 20 20]]
random1:  [[0.88773685 0.76548052 0.33250456]
 [0.24390284 0.93470809 0.62475956]]
random2:  [[-0.21270593 -0.02219115 -1.04734924]
 [-2.04167354  0.16727721 -0.09497437]]


In [3]:
np.dtype('i4')

dtype('int32')

In [4]:
np.dtype('?')

dtype('bool')

## 속성

In [5]:
# 배열 속성알아보기
print(a.ndim) #  배열 차원수 또는 배열의 축수
print(a.shape) # 배열 각 차원 크기 표현
print(a.dtype) # 배열 요소의 데이터 타입

print(b.ndim)
print(b.shape)

print(c.ndim)
print(c.shape)

1
(6,)
int32
2
(2, 3)
3
(2, 2, 3)


In [6]:
# 배열 모양새
print(a.size) # 전체 배열 요소 수
print(b.size)
print(c.size)

6
6
12


## 전치

In [7]:
# 배열의 전치
print(a.T) # 전치, 동일한 결과
print(b.T) # 전치, 행과 열이 뒤바뀜

[0 1 2 3 4 5]
[[0 3]
 [1 4]
 [2 5]]


In [8]:
c.transpose(0,2,1) #첫번째 차원은 그대로 두고, 두번째, 세번째 축을 변경

array([[[ 0,  3],
        [ 1,  4],
        [ 2,  5]],

       [[ 6,  9],
        [ 7, 10],
        [ 8, 11]]])

In [9]:
c.swapaxes(0,1) #세번째 차원은 그대로 두고, 첫번째, 두번째 축을 변경

array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 3,  4,  5],
        [ 9, 10, 11]]])

## 인덱싱과 슬라이싱

In [10]:
# 배열 인덱싱
print(b[0, 1]) # b 2차원 배열의 첫번째 행의 두번째 열
print(b[1, 2]) # b 2차원 배열의 두번째 행의 세번째 열
print(c[0,1,1]) # c 3차원 배열의 첫번째 차원의 두번째 행, 두번째 열

1
5
4


In [11]:
# 배열 슬라이싱
print(c[0, :2, :2]) # c 3차원 배열의 첫번째 차원에서 두번째 행까지의 두번째 열까지

[[0 1]
 [3 4]]


## 모양새 바꾸기

In [12]:
b = np.array([(0,1,2), (3,4,5)], dtype="uint8") # 2차원 배열 2x3
print(b)

[[0 1 2]
 [3 4 5]]


In [13]:
# 배열을 모양을 변경
b.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]], dtype=uint8)

## fancy indexing

In [14]:
import numpy as np

fancy_arr = np.arange(3*3*2, dtype="uint8")
fancy_arr = fancy_arr.reshape(3,2,3)
fancy_arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]], dtype=uint8)

In [15]:
# fancy indexing
# 1차원의 첫번째 요소에서 두번째 배열
fancy_arr[[0],[1]]

array([[3, 4, 5]], dtype=uint8)

In [16]:
fancy_arr[[0],[1],[2,1,0]]

array([5, 4, 3], dtype=uint8)

In [17]:
fancy_arr[[-1],[0],[2,1,0]]

array([14, 13, 12], dtype=uint8)

## 배열 산술 연산

In [18]:
# 배열 산술
arr1 = np.random.rand(2,3)
arr1

array([[0.8672563 , 0.20611571, 0.97653586],
       [0.68910415, 0.67174434, 0.06180195]])

In [19]:
arr2 = np.random.randn(2,3)
arr2

array([[-0.26028744,  0.9972101 , -1.0604569 ],
       [ 1.76113402, -0.75508207,  0.76489702]])

In [20]:
arr3 = arr1 * arr2
arr3

array([[-0.22573592,  0.20554066, -1.03557419],
       [ 1.21360476, -0.50722211,  0.04727213]])

In [21]:
arr4 = np.ones((2,3)) * 2 # 모든 요소를 2로 곱함
arr4

array([[2., 2., 2.],
       [2., 2., 2.]])

In [22]:
arr2 ** 2 # 모든 요소 2로 거듭제곱

array([[0.06774955, 0.99442798, 1.12456885],
       [3.10159305, 0.57014894, 0.58506746]])

##  배열 합치기 및 나누기

In [23]:
# 배열 합치기
np.concatenate([b,b])

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]], dtype=uint8)

In [24]:
# 배열 합치기(열기준)
np.concatenate([b,b], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]], dtype=uint8)

In [25]:
a1 = np.array([(0,1,2,3), (4,5,6,7)] , dtype="uint8") # 2차원 배열
b1 = np.array([(10,11,12,13), (14,15,16,17)] , dtype="uint8") # 2차원 배열

# 행기준으로 합치기
np.vstack((a1,b1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [10, 11, 12, 13],
       [14, 15, 16, 17]], dtype=uint8)

In [26]:
# 열기준으로 합치기
np.hstack((a1,b1))

array([[ 0,  1,  2,  3, 10, 11, 12, 13],
       [ 4,  5,  6,  7, 14, 15, 16, 17]], dtype=uint8)

In [27]:
b2 = np.array([(0,1,2,3), (4,5,6,7)] , dtype="uint8") # 2차원 배열

# 행기준으로 2부분 나누기
np.split(b2,2)

[array([[0, 1, 2, 3]], dtype=uint8), array([[4, 5, 6, 7]], dtype=uint8)]

In [28]:
# 행기준으로 2부분 나누기
np.vsplit(b2,2)

[array([[0, 1, 2, 3]], dtype=uint8), array([[4, 5, 6, 7]], dtype=uint8)]

In [29]:
#열기준 2부분 나누기
np.hsplit(b2,2)

[array([[0, 1],
        [4, 5]], dtype=uint8),
 array([[2, 3],
        [6, 7]], dtype=uint8)]

## 조건문으로 배열 추출하기

In [30]:
arr1 = np.random.rand(2,3)
arr2 = np.random.randn(2,3)
arr2 = arr2 ** 2

arr2

array([[0.05599537, 4.40283434, 0.26912427],
       [0.41578299, 0.03574639, 0.91715461]])

In [31]:
# 조건, arr2 배열 요소 가운데 1보다 큰 수만 추출
arr2[ arr2 > 1]

array([4.40283434])

In [32]:
# 조건에 부합하는 인덱스
np.where( arr2 > 1)

(array([0], dtype=int64), array([1], dtype=int64))

In [33]:
# 조건에 부합하면 ‘Yes’를 출력
np.where( arr2 > 1, 'Yes', arr1)

array([['0.2106373102024346', 'Yes', '0.7361306867744529'],
       ['0.5913212849864589', '0.7024440577978812',
        '0.03819080961205423']], dtype='<U32')